import { TableData } from "../../../types/types";

export const initialTableData: TableData[] = [
    { id: 1, name: 'Wierzchosława', age: 63, bornDate: '1999-06-15', biography: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' },
    { id: 2, name: 'Bartek', age: 32, bornDate: '1991-03-27', biography: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem.' },
    { id: 3, name: 'Kasia', age: 18, bornDate: '2005-02-11', biography: 'Nulla eget eleifend libero.' },
    { id: 4, name: 'Michał', age: 45, bornDate: '1978-07-23', biography: 'Fusce accumsan, justo et pulvinar tincidunt, lorem nisl.' },
    { id: 5, name: 'Natalia', age: 29, bornDate: '1994-12-31', biography: 'Integer fringilla dui nec magna dignissim, a luctus velit dapibus. Integer fringilla dui nec magna dignissim, a luctus velit dapibus. Integer fringilla dui nec magna dignissim, a luctus velit dapibus.' },
    { id: 6, name: 'Piotr', age: 27, bornDate: '1996-09-17', biography: 'Vestibulum eu lacus ac mi facilisis tristique. Curabitur vel enim a dolor suscipit faucibus.' },
    { id: 7, name: 'Monika', age: 22, bornDate: '1999-05-07', biography: 'Donec vel eros malesuada, pulvinar velit vel, maximus justo. Nam finibus varius libero vel sollicitudin.' },
    { id: 8, name: 'Krzysztof', age: 37, bornDate: '1986-11-11', biography: 'Cras eu turpis vel enim fermentum bibendum. Aenean vel sem non odio efficitur malesuada. Sed a malesuada quam.' },
    { id: 9, name: 'Magda', age: 31, bornDate: '1992-02-25', biography: 'Morbi vitae diam in massa mattis aliquam.' },
    { id: 10, name: 'Tomasz', age: 28, bornDate: '1995-09-25', biography: 'In hac habitasse platea dictumst.' },
    { id: 11, name: 'Karolina', age: 26, bornDate: '1997-01-01', biography: 'Curabitur vel enim a dolor suscipit faucibus.' },
    { id: 12, name: 'Kamil', age: 33, bornDate: '1988-08-16', biography: 'Quisque quis leo lobortis, pulvinar nisi vitae, convallis metus.' },
    { id: 13, name: 'Ewa', age: 41, bornDate: '1982-04-30', biography: 'Vestibulum euismod, nibh sit amet fermentum dictum, quam nisi.' },
    { id: 14, name: 'Mariusz', age: 49, bornDate: '1974-05-09', biography: 'Integer fringilla dui nec magna dignissim, a luctus velit dapibus.' },
    { id: 15, name: 'Sylwia', age: 23, bornDate: '1998-02-14', biography: 'Vivamus blandit mauris sed velit dignissim, non mattis felis ultrices.' },
    { id: 16, name: 'Jan', age: 36, bornDate: '1985-07-28', biography: 'Nam vulputate quam ac diam ullamcorper bibendum.' },
    { id: 17, name: 'Janusz', age: 42, bornDate: '1981-02-03', biography: 'Praesent euismod vulputate odio, eget bibendum nisi ultrices at.' },
    { id: 18, name: 'Maria', age: 27, bornDate: '1996-11-18', biography: 'Nulla facilisi. Nullam tincidunt augue quis mauris bibendum, ac pellentesque mi ullamcorper.' },
    { id: 19, name: 'Piotr', age: 18, bornDate: '2005-07-29', biography: 'Mauris vel vestibulum nibh. Sed eget vestibulum neque, sit amet rhoncus odio.' },
    { id: 20, name: 'Aleksandra', age: 35, bornDate: '1988-04-22', biography: 'Suspendisse a nunc tortor. Vivamus accumsan fermentum lectus, ut tristique risus.' },
    { id: 21, name: 'Katarzyna', age: 29, bornDate: '1992-12-01', biography: 'Curabitur euismod justo id lectus semper euismod.' },
    { id: 22, name: 'Jakub', age: 25, bornDate: '1998-09-10', biography: 'Ut vel aliquam odio, ac efficitur augue. Nam eu quam eu tellus maximus rhoncus.' },
    { id: 23, name: 'Magdalena', age: 47, bornDate: '1976-06-28', biography: 'Nam finibus varius libero vel sollicitudin.' },
    { id: 24, name: 'Krzysztof', age: 51, bornDate: '1972-03-17', biography: 'Suspendisse ut ullamcorper quam. Sed eleifend arcu at justo dignissim pharetra.' },
    { id: 25, name: 'Dominika', age: 22, bornDate: '2001-10-12', biography: 'Aenean vel sem non odio efficitur malesuada. Sed a malesuada quam.' },
    { id: 26, name: 'Bartłomiej', age: 39, bornDate: '1984-07-23', biography: 'Phasellus eget blandit velit. Sed bibendum luctus mauris, nec eleifend elit tristique id.' },
    { id: 27, name: 'Aneta', age: 32, bornDate: '1989-04-09', biography: 'In vel magna rhoncus, vestibulum velit ut, ultrices risus.' },
    { id: 28, name: 'Tomasz', age: 44, bornDate: '1979-11-02', biography: 'Maecenas ut neque id mauris tristique fermentum.' },
];